"""make uploader_id non-nullable

Revision ID: 086563cf5438
Revises: bd1318844516
Create Date: 2021-03-21 23:30:43.767093

"""
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "086563cf5438"
down_revision = "bd1318844516"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "memes", "uploader_id", existing_type=postgresql.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "memes", "uploader_id", existing_type=postgresql.UUID(), nullable=True
    )
    # ### end Alembic commands ###
