"""add uploaded_at to meme

Revision ID: d345189d37a8
Revises: 308cc3a2fa1e
Create Date: 2021-02-22 02:30:52.595629

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d345189d37a8"
down_revision = "308cc3a2fa1e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memes", sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memes", "uploaded_at")
    # ### end Alembic commands ###
