"""unique filename for uploader constraint

Revision ID: ecd54080734a
Revises: d345189d37a8
Create Date: 2021-02-28 20:35:08.700906

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ecd54080734a"
down_revision = "d345189d37a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_uploader_filename_uc", "memes", ["filename", "uploader_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_uploader_filename_uc", "memes", type_="unique")
    # ### end Alembic commands ###
