version: 2
updates:
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
