name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env files
        run: |
          echo "POSTGRES_SERVER=db" >> api/.env
          echo "POSTGRES_USER=memezer" >> api/.env
          echo "POSTGRES_DB=memezerlocal" >> api/.env
          echo "POSTGRES_PASSWORD=password" >> api/.env
          echo "JWT_SECRET_KEY=b8cae3ab4b7e6773ecb3f6848cfd816d161b86880cae978bb80d33f34bfdca18" >> api/.env
          echo "MEDIA_PATH=/media" >> api/.env
          echo "" >> web/.env
      - name: Pull containers
        run: docker-compose pull
      - name: Build containers
        run: docker-compose build
      - name: Start db container
        run: docker-compose up -d db
      - name: Run migration
        run: docker-compose run api upgrade
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:8080"
          working-directory: ./e2e
          start: docker-compose up -d api
